[package]
name = "cd-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
cd-core = { workspace = true }
cd-ecs = { workspace = true }
cd-map = { workspace = true }
cd-telemetry = { workspace = true }
cd-data = { workspace = true }
cd-depot = { workspace = true }
notify   = { workspace = true }
hecs = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
rand_chacha = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
