[package]
name = "cd-app"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
cd-core = { workspace = true }
cd-ecs = { workspace = true }
cd-map = { workspace = true }
cd-engine = { workspace = true }
cd-net = { workspace = true }
cd-data = { workspace = true }
tokio = { workspace = true, features = ["signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
bevy = { workspace = true, optional = true }
bevy-inspector-egui = { workspace = true, optional = true }


[lints]
workspace = true

[features]
default = []
dev_editor = ["bevy", "bevy-inspector-egui"]
