[package]
name = "cd-brp"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
cd-core = { workspace = true, features = ["bevy"] }
serde = { workspace = true }
bevy = { workspace = true }
rand = "0.10.1"
thiserror = { workspace = true }
seahash = "4.1"
tracing = { workspace = true }

[lints]
workspace = true
