[package]
name = "cd-ecs"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
cd-core = { workspace = true }
cd-common = { workspace = true }
cd-map = { workspace = true }
cd-data = { workspace = true }
bevy_ecs = { workspace = true }
serde = { workspace = true }
ahash = { workspace = true }

[lints]
workspace = true
