[package]
name = "cd-common"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
thiserror = { workspace = true }
bevy = { workspace = true, optional = true }
bevy-inspector-egui = { workspace = true, optional = true }

[lints]
workspace = true

[features]
default = []
bevy = ["dep:bevy"]
dev_editor = ["dep:bevy-inspector-egui", "bevy"]
